### ISSUE TITLE
while installing: npm ERR! code ENOLOCAL

### ISSUE THREAD

**Issue by eugengaspar** [fnlctrl/testcafe-browser-provider-webdriverio#1]
hi @fnlctrl .
I've just tried to install this package, according to the readme file, but I'm encountering this error:

> npm ERR! code ENOLOCAL
npm ERR! Could not install from "github.com:fnlctrl\testcafe-browser-provider-webdriverio.git" as it does not contain a package.json file.

ps: besides node **v8.12.0**

**_LATER EDIT_**:
after trying to npm clear cache -f, rm node_modules, both and some other tries, what sorted out the installation of the package was: delete the _node_modules_ and adding the repo path directly into my package.json:
 

> "devDependencies": {
...
    `"testcafe-browser-provider-webdriverio": "git+https://github.com/fnlctrl/testcafe-browser-provider-webdriverio.git"`
... }

**Comment by fnlctrl** [comment]
Sorry I haven't tested with the command myself. Using https:// seems to work. I've updated the readme accordingly.
