### ISSUE TITLE
Wait for session delete in closeBrowser()

### ISSUE THREAD

**Issue by lesn1kk** [fnlctrl/testcafe-browser-provider-webdriverio#7]
Using `chromedriver` standalone with `testcafe` and `testcafe-browser-provider-webdriverio` plugin, after running tests, `chromedriver` needs to be stopped explicitily.

In same time after tests, `testcafe.close()`  is called which triggers `closeBrowser()` from `testcafe-browser-provider-webdriverio`. 

However because `chromedriver` stops before `deleteSession()` is called, `webdriver` throws exception ` ERROR webdriver: Request failed due to Error: connect ECONNREFUSED 127.0.0.1:9515`.

Solution would be to wait for `deleteSession()` and make sure `testcafe.close()` is called before `chromedriver.stop()`. 

So in `async closeBrowser()` add ``` await``` keyword to `deleteSession()` call.

```javascript
async closeBrowser(id) {
    await this.browsers[id].deleteSession();
    delete this.browsers[id];
    clearInterval(this.heartbeats[id]);
    delete this.heartbeats[id];
},
```

Best regards

**Comment by fnlctrl** [comment]
Thanks!
